### ISSUE TITLE
Transaction::is_transaction_approved() seems to be broken

### ISSUE THREAD

**Issue by agibalov** [lemmetry/payeezy#3]
I'm trying to use 1.0.5 like this:

``` python
loki2302@ubuntu:~/ggg/payeezy$ python3
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from payeezy import transactions
>>> t = transactions.Transaction()
>>> t.is_transaction_approved()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/loki2302/ggg/payeezy/payeezy/transactions.py", line 132, in is_transaction_approved
    http_status_code = response.status_code
AttributeError: 'NoneType' object has no attribute 'status_code'
```

But it does not seem to work. Am I missing something?

**Comment by lemmetry** [comment]
Hello @loki2302 ,
please see [most recent commit](https://github.com/lemmetry/payeezy/commit/5ff29ff8707e1b756d6b33a7505222cda0796296), you can use [this routines](https://github.com/lemmetry/payeezy/blob/master/payeezy/api.py) to submit purchases and authorizations (more functions will be added).

Don't forget to declare you sandbox/production variables like [here](https://github.com/lemmetry/payeezy/blob/master/example.py#L4).

Please feel free to let me know if you have any questions.
